name: env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python y ciencia de datos
  - python=3.10
  - rdkit
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - ipykernel
  - jupyterlab

  # Herramientas necesarias para instalar paquetes desde GitHub
  - git
  - pip
  - setuptools
  - wheel

  # Paquetes vía pip (incluye MolForge directamente desde GitHub)
  - pip:
      - selfies
      - sentencepiece
      - gdown
      - rich
      - "molforge @ git+https://github.com/knu-lcbc/MolForge.git"