name: molforge
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - rdkit=2022.09.3
  - pip
  - ipykernel
  - jupyterlab
  - pandas=1.5.2
  - matplotlib=3.5.1
  - seaborn=0.12.2
  - tqdm=4.64.1
  - numpy
  - pip:
      - selfies==2.1.1
      - sentencepiece==0.1.95
      - gdown==4.2.0
      - rich
      - git+https://github.com/knu-lcbc/MolForge.git
