name: env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python y ciencia de datos
  - python=3.10
  - rdkit
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - ipykernel
  - jupyterlab

  # Herramientas varias
  - pip

  # Paquetes que instalamos por pip (incluye MolForge desde GitHub)
  - pip:
      - selfies
      - sentencepiece
      - gdown
      - rich
      - git+https://github.com/knu-lcbc/MolForge.git
